language: cpp
os: linux
dist: xenial

matrix:
  include:
    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env: CXX=g++-4.7

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++17
      before_script:
        - CXX=g++-7
        - CXXSTD=-std=c++17


    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
        - CXXSTD=-std=c++20
      before_script:
        - CXX=g++-8
        - CXXSTD=-std=c++20

    - dist: xenial
      compiler: clang
      env:
        - CXX=clang++


    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['clang-7']
      env:
        - CXX=clang++-7

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - CXX=clang++

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['clang-7', 'clang-tidy-7']
      env:
        - CXX=clang++-7
        - CLANG_TIDY=clang-tidy-7
      script:
        - make -kj3 clang-tidy

    - language: python
      python:
        - "3.6"
      sudo: required
      install:
        - pip install conan conan-package-tools
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=lasote/conangcc7
      script:
        - python .conan/build.py

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
      script:
        - $CXX --version
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - cmake --build . --target test



script:
  - cmake --version
  - clang --version
  - gcc --version
  - cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  # - sudo pip install --upgrade pip
  # - sudo pip install cmake
  # - ls /usr/local/bin
  # - /usr/local/bin/cmake --version
  # - /usr/local/bin/cmake -H. -Bbuild
  # - cat /home/travis/build/FirstLoveLife/Rider-Faiz/build/CMakeFiles/CMakeOutput.log
  - cd build
  - make
  - make test
